name: Train and Save Model Artifact

on:
  push:
    paths:
      - '3.Workflow-CI/MLProject/**'
      - '2.Membangun_model/ionosphere_preprocessing.csv'
      - '.github/workflows/train_and_save_artifact.yml'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3.Workflow-CI/MLProject
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r ../../2.Membangun_model/requirements.txt

      - name: Run training script
        run: python modelling.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            mlruns/
            classification_report.txt
